wetaxi/taxi/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
import wetaxi.taxi.views

urlpatterns = patterns('',
	url(r'^dashboard/$', wetaxi.taxi.views.dashboard, name='dashboard'),
	url(r'^update/profile/$', wetaxi.taxi.views.update_profile, name='update_profile'),
	url(r'^driver/profile/$', wetaxi.taxi.views.driver_profile, name='driver_profile'),
	url(r'^drivers/list/$', wetaxi.taxi.views.drivers_list, name='drivers_list'),
	url(r'^mylist/$', wetaxi.taxi.views.taxi_mylist, name='taxi_mylist'),
	url(r'^new/$', wetaxi.taxi.views.taxi_new, name='taxi_new'),
	url(r'^features/$', wetaxi.taxi.views.taxi_features, name='taxi_features'),
	url(r'^icon/$', wetaxi.taxi.views.taxi_icon, name='taxi_icon'),
	url(r'^remove/$', wetaxi.taxi.views.taxi_remove, name='taxi_remove'),
	url(r'^rate/$', wetaxi.taxi.views.taxi_rate, name='taxi_rate'),
	url(r'^rate/view/$', wetaxi.taxi.views.taxi_rate_view, name='taxi_rate_view'),
	url(r'^booking/schedule/$', wetaxi.taxi.views.booking_schedule, name='booking_schedule'),
	url(r'^schedule/events/$', wetaxi.taxi.views.taxi_schedule_events, name='taxi_schedule_events'),
	url(r'^booking/(?P<pk>\w+)/$', wetaxi.taxi.views.taxi_booking, name='taxi_booking'),
	url(r'^enquiry/$', wetaxi.taxi.views.taxi_booking_enquiry, name='taxi_booking_enquiry'),
	url(r'^cancel/enquiry/(?P<pk>\w+)/$', wetaxi.taxi.views.taxi_cancel_enquiry, name='taxi_cancel_enquiry'),
	url(r'^confirm/booking/(?P<pk>\w+)/$', wetaxi.taxi.views.taxi_confirm_booking, name='taxi_confirm_booking'),
)

wetaxi/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from main import views
admin.autodiscover()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'wetaxi.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.index, name='index'),
    url(r'^login/', views.login, name='login'),
    url(r'^logout/', views.logout, name='logout'),
	url(r'^register/taxi/', views.register_taxi, name='register_taxi'),
    url(r'^taxi/view/(?P<pk>\w+)/$', views.taxi_view, name='taxi_view'),
    url(r'^taxi/availability/(?P<pk>\w+)/$', views.taxi_availability, name='taxi_availability'),
    url(r'^search/taxi/', views.search_taxi, name='search_taxi'),
    url(r'^taxi/booking/confirm/(?P<pk>\w+)/$', views.taxi_booking_confirm, name='taxi_booking_confirm'),
    url(r'^taxi/send/enquiry/(?P<pk>\w+)/$', views.taxi_send_enquiry, name='taxi_send_enquiry'),
    url(r'^register/user/', views.register_user, name='register_user'),
	# Views of taxi app
	url(r'^taxi/', include('wetaxi.taxi.urls', namespace='taxi')),

    # Ajax views
    url(r'^ajax/district/', views.ajax_district, name='ajax_district'),
    url(r'^ajax/circle/', views.ajax_circle, name='ajax_circle'),
    url(r'^ajax/taxi/', views.ajax_taxi, name='ajax_taxi'),
)

wetaxi/main/models.py
from django.db import models

# Create your models here.

wetaxi/taxi/models.py
from django.db import models
from django.contrib.auth.models import User

from wetaxi.users.models import UserProfile
from wetaxi.static_items.models import Circle

class TaxiType(models.Model):
	taxi_type = models.CharField(max_length=100)

class TaxiProfile(models.Model):
	taxi_type = models.ForeignKey(TaxiType)
	owner = models.ForeignKey(UserProfile)
	display_name = models.CharField(max_length=255, null=True, blank=True)
	taxi_model = models.CharField(max_length=255, null=True, blank=True)
	taxi_number = models.CharField(max_length=255, null=True, blank=True)
	seat_capacity = models.CharField(max_length=32, null=True, blank=True)
	icon_url = models.URLField(max_length=225, null=True, blank=True)
	circle = models.ForeignKey(Circle)
	is_valid = models.NullBooleanField(default=None)
	feature = models.TextField()
	date_registered = models.DateTimeField(auto_now=True)

	def __unicode__(self):
		return str(self.display_name) 

	def get_rate(self):
		try:
			taxi_rate = TaxiRate.objects.get(taxi=self)
			return taxi_rate.rate
		except:
			return None	

class TaxiRate(models.Model):
	taxi = models.ForeignKey(TaxiProfile)
	rate = models.CharField(max_length=100, null=True, blank=True)
	with_ac = models.CharField(max_length=255, null=True, blank=True)

class TaxiGellery(models.Model):
	taxi = models.ForeignKey(TaxiProfile)
	image_url = models.URLField(max_length=255)	

class DriverProfile(models.Model):
	name = models.CharField(max_length=255)
	address = models.TextField()
	email = models.EmailField(max_length=254)
	phone = models.CharField(max_length=20,null=True, blank=True)
	mobile = models.CharField(max_length=20,null=True, blank=True)
	added_by = models.ForeignKey(UserProfile)

	def __unicode__(self):
		return self.name

class TaxiBookingSchedule(models.Model):
	taxi = models.ForeignKey(TaxiProfile)
	booking_from_date = models.DateTimeField()
	booking_to_date = models.DateTimeField()
	route = models.TextField()
	contact_person = models.TextField()
	contact_number = models.CharField(max_length=255)
	contact_address = models.TextField() 
	booking_id = models.SlugField(db_index=True, unique=True)
	is_enquiry = models.BooleanField(default=False)
	is_confirmed = models.BooleanField(default=False)
	description = models.TextField(blank=True)
	enquiry_date = models.DateTimeField(auto_now=True)
	passenger = models.ForeignKey(UserProfile, null=True, blank=True)

	def __unicode__(self):
		return str(self.taxi) + ' - ' + 	str(self.booking_from_date.date()) + '---' + str(self.booking_to_date.date()) + ')'

class BookingPayment(models.Model):
	booking = models.ForeignKey(TaxiBookingSchedule)
	advance_payment = models.FloatField(null=True, blank=True)
	total_payment = models.FloatField(null=True, blank=True)
	is_closed = models.BooleanField(default=False)
	is_paid = models.BooleanField(default=False)



		

wetaxi/main/forms.py
from django import forms

class TaxiRegisterForm(forms.Form):
	email = forms.CharField(max_length=255)
	password = forms.CharField(max_length=32)
	mobile = forms.CharField(min_length=10, max_length=10)

wetaxi/taxi/forms.py
from django import forms

class TaxiAddForm(forms.Form):
	taxitype = forms.CharField(max_length=32)
	name = forms.CharField(max_length=255)
	model = forms.CharField(max_length=255)
	taxinumber = forms.CharField(max_length=255)
	seats = forms.CharField(max_length=255)
	state =  forms.CharField(max_length=255)
	district = forms.CharField(max_length=255)
	circle = forms.CharField(max_length=255)


class TaxiIconForm(forms.Form):
	taxitype = forms.CharField(max_length=32)
	taxi = forms.CharField(max_length=32)
	taxi_icon = forms.FileField()	

class TaxiRateForm(forms.Form):
	taxitype = forms.CharField(max_length=20)
	taxi = forms.CharField(max_length=20)
	taxi_rate = forms.CharField(max_length=20)

class UpdateProfileForm(forms.Form):
	first_name = forms.CharField(max_length=255)	
	address = forms.CharField(max_length=1024)
	state = forms.CharField(max_length=20)
	district = forms.CharField(max_length=20)
	circle = forms.CharField(max_length=20)

class DriverProfileForm(forms.Form):
	name = forms.CharField(max_length=255)
	address = forms.CharField(max_length=255)
	email = forms.CharField(max_length=255)
	phone = forms.CharField(max_length=20)
	mobile = forms.CharField(max_length=20)

		

wetaxi/main/views.py
from django.shortcuts import *
from django.http import HttpResponse, Http404
from django.core.context_processors import csrf
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.core.urlresolvers import reverse

from wetaxi.main.forms import TaxiRegisterForm
from wetaxi.wetaxiconfigs.user_types import UserType
from wetaxi.wetaxiconfigs.email import send_email
from wetaxi.users.models import UserProfile
from wetaxi.static_items.models import Country, State, District, Circle
from wetaxi.taxi.models import TaxiProfile, TaxiBookingSchedule

from django.db.models import Q

import datetime

import json

#Ajax views
def ajax_district(request):
	response = {}
	if 'state' in request.GET and request.GET['state']:
		state = request.GET['state']
	else:
		raise Http404

	state_obj = get_object_or_404(State, pk=state)
	response.update({'districts': District.objects.filter(state=state_obj)})
	return render_to_response('ajax_districts.html', response)

def ajax_circle(request):
	response = {}
	if 'district' in request.GET and request.GET['district']:
		district = request.GET['district']
	else:
		raise Http404
	district_obj = get_object_or_404(District, pk=district)
	response.update({'circles': Circle.objects.filter(district=district_obj)})
	return render_to_response('ajax_circles.html', response)		

def ajax_taxi(request):
	response = {}
	if 'taxitype' in request.GET and request.GET['taxitype']:
		taxitype = request.GET['taxitype']
	else:
		raise Http404
	
	if 'user' in request.GET and request.GET['user']:
		user = request.GET['user']
	else:
		raise Http404
	user_obj = get_object_or_404(UserProfile, pk=user)
	response.update({'taxi_list': TaxiProfile.objects.filter(taxi_type=taxitype, owner=user_obj)})
	return render_to_response('ajax_taxi.html', response)

#Index view for main page ---Created by Viru---
def index(request):
	response = {}
	response.update(csrf(request))
	response.update({'user_profiles': UserProfile.objects.filter(user_type='1').order_by('-pk')[:10]})
	response.update({'states': State.objects.all()})
	return render_to_response('index.html', response)

def register_taxi(request):
	response = {}
	response.update(csrf(request))

	if request.method == 'GET':
		return render_to_response('index.html', response)

	if request.method == 'POST':
		form = TaxiRegisterForm(request.POST)
		if form.is_valid():
			response.update({'form':form})

			if 'user_type' in request.POST and request.POST['user_type']:
				user_type = request.POST['user_type']
				response.update({'user_type':user_type})
			else:
				response.update({'error':True})
				return render_to_response('index.html', response)

			try:
				user = User.objects.get(username=form.cleaned_data['email'])
			except:
				user = User(username=form.cleaned_data['email'], email=form.cleaned_data['email'])
				user.set_password(form.cleaned_data['password'])
				user.save()
				user_profile = UserProfile(user=user, user_type=user_type, phone=form.cleaned_data['mobile'])
				user_profile.save()
			else:
				response.update({'user_exists':True})
				return render_to_response('index.html', response)	
			
			if user_type == UserType.types['Taxi']:
				return render_to_response('taxi_dashboard.html', response)
			else:
				return render_to_response('passenger_dashboard.html', response)	

		else:
			response.update({'form':form})
			response.update({'form_error':True})
			return render_to_response('index.html', response)

def register_user(request):
	response = {}
	response.update(csrf(request))

	if request.method == 'GET':
		return render_to_response('index.html', response)

	if request.method == 'POST':
		response.update({'taxi':get_object_or_404(TaxiProfile, pk=request.POST['taxiId'])})
		form = TaxiRegisterForm(request.POST)
		if form.is_valid():
			response.update({'form':form})

			try:
				user = User.objects.get(username=form.cleaned_data['email'])
			except:
				user = User(username=form.cleaned_data['email'], email=form.cleaned_data['email'])
				user.set_password(form.cleaned_data['password'])
				user.save()
				user_profile = UserProfile(user=user, user_type=UserType.types['Passenger'], phone=form.cleaned_data['mobile'])
				user_profile.save()
			else:
				response.update({'email_exists':True})
				return render_to_response('taxi_availability.html', response)	
			
			user = authenticate(username=form.cleaned_data['email'], password=form.cleaned_data['password'])	
			auth_login(request, user)
			return HttpResponseRedirect('/taxi/booking/confirm/'+ request.POST['taxiId'] +'/')	

		else:
			response.update({'form':form})
			response.update({'form_error':True})
			return render_to_response('taxi_availability.html', response)


def login(request):
	response = {}
	response.update(csrf(request))

	if request.method == 'GET':
		return HttpResponseRedirect('/')

	if request.method == 'POST':
		username = request.POST.get('email','')
		password = request.POST.get('password', '')
		user = authenticate(username=username, password=password)	
		if user is not None:
			auth_login(request, user)
			try:
				user_profile = UserProfile.objects.get(user=user)
			except:
				return HttpResponse('UserProfile Not Found!')

			if user_profile.user_type == UserType.types['Taxi']:
				return HttpResponseRedirect(reverse('taxi:dashboard')) 		
			elif user_profile.user_type == UserType.types['Passenger']:
				if 'taxiId' in request.POST and request.POST['taxiId']:
					return HttpResponseRedirect('/taxi/booking/confirm/'+ request.POST['taxiId'] +'/')	
				return HttpResponse('passenger')
				return HttpResponseRedirect(reverse('passenger:dashboard')) 
		else:
			response.update({'invalid_user': True})
			return render_to_response('index.html', response)

def logout(request):
	response = {}
	response.update(csrf(request))

	auth_logout(request)
	return HttpResponseRedirect('/')	


def taxi_view(request,pk):
	response = {}
	response.update(csrf(request))
	
	response.update({'states': State.objects.all()})

	user_profile = get_object_or_404(UserProfile, pk=pk)
	response.update({'user_profile': user_profile})
	response.update({'taxi_profiles': TaxiProfile.objects.filter(owner=user_profile)})
	return render_to_response('taxi_view.html', response)

def search_taxi(request):
	response = {}
	response.update(csrf(request))
	response.update({'states': State.objects.all()})

	if 'circle' in request.GET and request.GET['circle']:
		circle = request.GET['circle']
	else:
		raise Http404	

	circle_obj = get_object_or_404(Circle, pk=circle)
	response.update({'circle': circle_obj})
	response.update({'user_profiles': UserProfile.objects.filter(circle=circle_obj)})
	return render_to_response('taxi_list.html', response)	
	
def taxi_availability(request, pk):
	response = {}
	response.update(csrf(request))
	taxi = get_object_or_404(TaxiProfile, pk=pk)
	response.update({'taxi':taxi})
	if 'login_error' in request.GET and request.GET['login_error']:
		response.update({'login_error':True})
	return render_to_response('taxi_availability.html', response)	

def taxi_booking_confirm(request, pk):
	response = {}
	response.update(csrf(request))
	taxi = get_object_or_404(TaxiProfile, pk=pk)
	response.update({'taxi':taxi})
	if not request.user.is_authenticated():
		return HttpResponseRedirect('/taxi/availability/'+ str(pk) + '/?login_error=1')
	
	response.update({'register_success':True})
	return render_to_response('taxi_availability.html', response)

def taxi_send_enquiry(request, pk):
	response = {}
	user = get_object_or_404(UserProfile, user=request.user)
	taxi = get_object_or_404(TaxiProfile, pk=pk)

	if 'fromDate' in request.POST and request.POST['fromDate']:
		from_date = request.POST['fromDate']
	else:
		raise Http404()

	if 'toDate' in request.POST and request.POST['toDate']:
		to_date = request.POST['toDate']
	else:
		raise Http404()

	person = request.POST['name']
	number = user.phone
	email = user.user.email
	route = request.POST['route']
	description = request.POST['description'] if 'description' in request.POST else 'Nil'

	from_date = from_date.split(' ')
	from_date = str(from_date[0]) + ' ' + str(from_date[1]) + ' ' + str(from_date[2])
	from_date = datetime.datetime.strptime(from_date, '%m/%d/%Y %I:%M %p')

	to_date = to_date.split(' ')
	to_date = str(to_date[0]) + ' ' + str(to_date[1]) + ' ' + str(to_date[2])
	to_date = datetime.datetime.strptime(to_date, '%m/%d/%Y %I:%M %p')

	if to_date < from_date:
		return HttpResponse(
			json.dumps(
					{'status':False, 'message':'Error: End Date cannot be less than Start Date !!'}
			),
			content_type = 'application/json'
		)

	if from_date < datetime.datetime.now():
		return HttpResponse(
			json.dumps(
					{'status':False, 'message':'Error: No Booking !!'}
			),
			content_type = 'application/json'
		)
  
	booking_id = 1000
	latest_booking_id = TaxiBookingSchedule.objects.all().order_by('-id')
	if latest_booking_id:
		booking_id = int(latest_booking_id[0].booking_id) + 1

	booked = TaxiBookingSchedule.objects.filter(Q(booking_from_date__range=(datetime.datetime.combine(from_date, datetime.datetime.min.time()), datetime.datetime.combine(from_date, datetime.datetime.max.time()))) | Q(booking_to_date__range=(datetime.datetime.combine(to_date, datetime.datetime.min.time()), datetime.datetime.combine(to_date, datetime.datetime.max.time()))) | Q(booking_from_date__lte=from_date, booking_to_date__gte=from_date), taxi=taxi, is_confirmed=True)

	if booked:
		return HttpResponse(
			json.dumps(
					{'status':False, 'message':'Error: This taxi is already booked for this date!!'}
			),
			content_type = 'application/json'
		)


	TaxiBookingSchedule.objects.create(taxi=taxi, booking_from_date=from_date, booking_to_date=to_date, contact_person=person, contact_number=number, route=route, booking_id=booking_id, is_enquiry=True, passenger=user)

	# SEND MAIL

	subject = 'Booking Enquiry'
	message = '<h3>You have a new Booking Enquiry</h3>'
	message += 'Name: ' + str(person) + '<br>'

wetaxi/main/templates/ajax_circles.html
<option value="0">Select</option>
{% for circle in circles %}
	<option value="{{circle.pk}}">{{circle.circle}}</option>
{% endfor %}

wetaxi/main/templates/ajax_districts.html
<option value="0">Select</option>
{% for district in districts %}
	<option value="{{district.pk}}" >{{district.district}}</option>
{% endfor %}	

wetaxi/main/templates/ajax_taxi.html
<option value="0">Select</option>
{% for taxi in taxi_list %}
	<option value="{{taxi.taxi_number}}">{{taxi.taxi_number}}</option>
{% endfor %}	

wetaxi/main/templates/calendar_modal.html
<div class="modal fade" id="calendarModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-lg">
   	<div class="modal-content">
      <div class="modal-header calendar-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h3></h3>
      </div>
      <div class="modal-body">
      	<div class="row">
  				<div class="col-lg-12">									
						<div class="pull-right">
        			<div class="btn-group">
            		<button class="btn btn-xs btn-primary" data-calendar-nav="prev">
                	<span class="entypo-left-circled"></span>Prev</button>
            		<button class="btn btn-xs " data-calendar-nav="today">Today</button>
            		<button class="btn btn-xs btn-primary" data-calendar-nav="next">Next
                	<span class="entypo-right-circled"></span>
            		</button>
        			</div>
        			<div class="btn-group">
                <button class="btn btn-xs btn-warning" data-calendar-view="year">Year</button>
                <button class="btn btn-xs btn-warning active" data-calendar-view="month">Month</button>
                <button class="btn btn-xs btn-warning" data-calendar-view="week">Week</button>
                <button class="btn btn-xs btn-warning" data-calendar-view="day">Day</button>
              </div>
    				</div>
    				<br><br>
						<div id="calendar"></div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

wetaxi/main/templates/footer.html
<div class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-collapse collapse" id="navbar-main">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <ul>
            <li><a href="" style="font-size:12px; color:grey;">Home</a></li>
            <li><a href="" style="font-size:12px;color:grey;">About</a></li>
            <li><a href="" style="font-size:12px;color:grey;">Blog</a></li>
            <li><a href="" style="font-size:12px;color:grey;">Contact</a></li>
          </ul>  
        <li>
          <ul>
            <li><a href="" style="font-size:12px; color:grey;"target="_blank">Terms of Service</a></li>
            <li><a href="" style="font-size:12px; color:grey;"target="_blank">Privacy Policy</a></li>
            <li><a href="" style="font-size:12px; color:grey;">Cancellation Policy</a></li>
            <li><a href="" style="font-size:12px; color:grey;">Refund Policy</a></li>
          </ul>
        </li> 
        <li>
          <span style="font-size:12px; color:grey;">Copyrights Wetaxi 2014. All Rights Reserved.</span>
        </li>   
      </ul>
    </div>
  </div>
</div>
</body>
</html>

wetaxi/main/templates/index.html
{% extends 'header.html' %}
          {% block content %}
          <div class="col-lg-9">
            <img src="/static/images/banner_new.png" width="750px;" height="300px;"><hr>
              <h4><span class="label label-success"><img src="/static/images/new-icon.png"> Registered Travel Companies</span></h4>
              <hr>
              {% for user_profile in user_profiles %}
                <div class="col-lg-4">
                  <div class="panel panel-success text-center ">
                    <div class="panel-heading">
                      {{user_profile.user.first_name}}
                      <p class="text-muted">{{user_profile.circle.circle}}</p>
                    </div>  
                    <div class="panel-body yellow">  
                      {% with user_profile.taxiprofile_set.all|first as icon %}
                        <div id="gallery" class="non-immediate-parent-container2">
                          <img src="{{icon.icon_url}}" class="resizeme">
                        </div>  
                      {% endwith %}
                      <br> 
                      <a href="/taxi/view/{{user_profile.pk}}/"><span class="label label-primary">Quick View</span></a>
                    </div>  
                  </div>
                </div> 
              {% endfor %}  
            </div>
          </div> 
        </div>
        {% endblock %}    

       

wetaxi/main/templates/taxi_list.html
{% extends 'header.html' %}


{% block content %}
	<div class="col-lg-9">
		<div class="alert alert-info">
			Search Result for Travel Companies in <strong><i>{{circle.circle}}</i></strong>
		</div>
		{% for user_profile in user_profiles %}
            <div class="col-lg-4">
              <div class="panel panel-success text-center ">
                <div class="panel-heading">
                  <font style="text-transform: uppercase;">{{user_profile.user.first_name}}</font>
                  <p class="text-muted">{{user_profile.circle.circle}}</p>
                </div>  
                <div class="panel-body yellow">  
                  {% with user_profile.taxiprofile_set.all|first as icon %}
                  <div id="gallery" class="non-immediate-parent-container2">
                    <img src="{{icon.icon_url}}" class="resizeme">
                  </div>  
                  {% endwith %}
                  <br> 
                  <a href="/taxi/view/{{user_profile.pk}}/"><span class="label label-primary">Quick View</span></a>
                </div>  
              </div>
            </div> 
        {% endfor %}
	</div>
{% endblock %}

wetaxi/main/templates/taxi_view.html
{% extends 'header.html' %}

{% block content %}
	
	<div class="col-lg-9">
		<div class="panel panel-success">
			<div class="panel panel-heading ">
				<h5><font style="text-transform: uppercase;">{{user_profile.user.first_name}}</font></h5>
			</div>
			<div class="panel-body">
				<p>
					{{user_profile.address1}}<br>
					<span class="glyphicon glyphicon-earphone"> {{user_profile.phone}}</span> | 
					<span class="glyphicon glyphicon-envelope"> {{user_profile.user.email}}</span>
					<br><br>
					<a href="" class="label label-info">SEND EMAIL</a>
					<a href="" class="label label-info">COMMENTS & RATINGS</a>		
				<p>		
			</div>
			<hr>
			{% for taxi_profile in taxi_profiles %}
				<div class="row">
					<div class="col-lg-3">
						<div id="gallery" class="non-immediate-parent-container2">
							<img src="{{taxi_profile.icon_url}}" class="resizeme">
						</div>	
					</div>	
					<div class="col-lg-9">
						<p class="text-muted">
							<strong>{{taxi_profile.display_name}} | {{taxi_profile.taxi_model}}</strong><br>
							{{taxi_profile.owner.user.first_name}}<br>
							{{taxi_profile.taxi_number}}<br>
							Seat Capacity : {{taxi_profile.seat_capacity}}<br>
							<strong class="text-success">Rs. {{taxi_profile.get_rate}} / Km</strong><br><br>
							<a href="/taxi/availability/{{taxi_profile.id}}/" class="btn btn-warning schedule">Check Availability</a> <button class="btn btn-success">Book Now</button>
						</p>	
					</div>
				</div>
			<hr>	
			{% endfor %}
		</div>	
	</div>

{% endblock %}